<?php

namespace modules\users\models;

use common\models\BaseUser;

/**
 * This is the model class for table "user".
 *
 * @property int $user_id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property int $status
 * @property string $created_at
 * @property string $updated_at
 */
class User extends BaseUser {
	public $password;
	public $confirm_password;
	/**
	 * {@inheritdoc}
	 */
	public static function tableName() {
		return 'user';
	}
	
	public function validatePassword($password) {
		return parent::validatePassword($password); // TODO: Change the autogenerated stub
	}
	
	/**
	 * {@inheritdoc}
	 */
	public function rules() {
		$rules = parent::rules();
		$rules['password'] = ['password', 'validateConfirmPassword', 'message' => 'mess'];
		return $rules;
	}
	
	public function validateConfirmPassword() {
		if (!$this->password && !$this->confirm_password) {
			return true;
		}
		
		if ($this->password !== $this->confirm_password) {
			$this->addError('confirm_password', 'Passwords do not match');
		}
		
		return $this->password === $this->confirm_password;
	}
	
	/**
	 * {@inheritdoc}
	 */
	public function attributeLabels() {
		return [
			'user_id' => 'User ID',
			'username' => 'Username',
			'auth_key' => 'Auth Key',
			'password_hash' => 'Password Hash',
			'password_reset_token' => 'Password Reset Token',
			'email' => 'Email',
			'status' => 'Status',
			'created_at' => 'Created At',
			'updated_at' => 'Updated At',
		];
	}
}
